### ISSUE TITLE
Security Issue (Amazon RDS - PostgreSQL

### ISSUE THREAD

**Issue by ousamabenyounes** [merj4/merj#170]
Hi @emma4evr ,

Your Amazon RDS PostgreSQL credentials are visible here:
https://github.com/merj4/merj/blob/52ea13a61fa36e6404cf1cb202f4d413fb7e5831/server/db.js

to remove it from your history:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Change your login/pwd on all your projects...If you use this password.

Regards,
Ousama.

**Comment by emma4evr** [comment]
Thank you so much Ousama! This issue has been resolved.

Regards,
Emma (Team Merj)
